/*=======================================================================================
** File Name:  sch_grpids.h
**
** Title:  Group IDs used by the CFS scheduler for DRONE mission
**
** $Author:    Auto-generated by Python scripts.
** $Revision:  $
** $Date:      2014-12-18
**
** Purpose:  This header file contains group IDs used by the CFS scheduler for mission DRONE.
**
**=====================================================================================*/

#ifndef _SCH_GRP_IDS_H_
#define _SCH_GRP_IDS_H_

/*
** Pragmas
*/

/*
** Include Files
*/

/*
** Local Defines
*/
#define SCH_GROUP_NONE  0x00000000
#define SCH_GROUP_MISC  0x00000004

#define SH_100HZ  0x01000000
#define SH_50HZ   0x02000000
#define SH_25HZ   0x04000000
#define SH_10HZ   0x08000000
#define SH_5HZ    0x21000000
#define SH_1HZ    0x22000000

#endif /* _SCH_GRP_IDS_H_ */

/*=======================================================================================
** End of file sch_grpids.h
**=====================================================================================*/
    